/**
 * Generates `src/__generated__/zodTypes.ts` by enumerating every
 * top-level identifier in zod's public module whose name starts
 * with `Zod[A-Z]`, then re-exporting them as
 * `export type { ... } from 'zod'`.
 *
 * Without this re-export, consumers' emitted `.d.ts` can fail with
 * `TS4023` ("X cannot be named") when zod types appear in inferred
 * return types of veto APIs — see `docs/veto-monorepo-usage.md`
 * for the full rationale.
 *
 * Wired into `build` (`"build": "pnpm build:zod && tsdown"`), so
 * every build refreshes the snapshot. In CI, fail the job if
 * `git diff --exit-code` is non-clean after `pnpm build`.
 *
 * Source of truth: `node_modules/zod/index.d.ts`. Re-export chains
 * are followed via the TypeScript compiler API so this script works
 * even when zod's public d.ts is just a re-export barrel.
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';

// typescript is a build-only dependency of veto (used by this codegen
// script). It is intentionally kept in `devDependencies` so it is not
// installed for veto's consumers.
// eslint-disable-next-line import-x/no-extraneous-dependencies
import {
  createProgram,
  ModuleKind,
  ModuleResolutionKind,
  ScriptTarget,
} from 'typescript';

// `pnpm --filter @fuf-stack/veto build:zod` runs with cwd set to the
// package directory, so process.cwd() always resolves to veto's root.
const PKG_ROOT = process.cwd();

const ZOD_DTS = resolve(PKG_ROOT, 'node_modules/zod/index.d.ts');
const ZOD_PKG = resolve(PKG_ROOT, 'node_modules/zod/package.json');
const OUT_FILE = resolve(PKG_ROOT, 'src/__generated__/zodTypes.ts');

const ZOD_NAME_RE = /^Zod[A-Z]/;

/**
 * Enumerates all top-level identifiers exported from zod whose name
 * matches `^Zod[A-Z]` (capitalized class/type/interface names).
 */
const collectZodNames = (): string[] => {
  const program = createProgram({
    rootNames: [ZOD_DTS],
    options: {
      module: ModuleKind.ESNext,
      target: ScriptTarget.ESNext,
      moduleResolution: ModuleResolutionKind.Bundler,
      noEmit: true,
      skipLibCheck: true,
    },
  });

  const sourceFile = program.getSourceFile(ZOD_DTS);
  if (!sourceFile) {
    throw new Error(`Cannot load ${ZOD_DTS}`);
  }

  const checker = program.getTypeChecker();
  const moduleSymbol = checker.getSymbolAtLocation(sourceFile);
  if (!moduleSymbol) {
    throw new Error(`Cannot resolve zod module symbol`);
  }

  return checker
    .getExportsOfModule(moduleSymbol)
    .map((symbol) => {
      return symbol.name;
    })
    .filter((name) => {
      return ZOD_NAME_RE.test(name);
    })
    .sort((a, b) => {
      return a.localeCompare(b);
    });
};

const renderFile = (names: readonly string[], zodVersion: string): string => {
  const entries = names
    .map((name) => {
      return `  ${name},`;
    })
    .join('\n');
  return `// AUTO-GENERATED by scripts/generate-zod-type-exports.ts — do not edit by hand.
//
// Regenerate with: pnpm --filter @fuf-stack/veto build:zod
// (also runs automatically via \`pnpm --filter @fuf-stack/veto build\`).
//
// Source of truth: node_modules/zod/index.d.ts (zod ${zodVersion}).
//
// Re-exports zod's capitalized Zod* identifiers so consumers' emitted
// .d.ts can name them when they appear in inferred return types from
// veto's API. Without these re-exports, \`tsc --build\` in a consumer
// raises TS4023 ("X cannot be named").
//
// A wildcard \`export type * from 'zod'\` is intentionally NOT used:
// zod also exposes lowercase identifiers (\`string\`, \`object\`,
// \`record\`, …) that veto re-uses as its own value-exports — a
// wildcard re-export causes rolldown to silently drop the colliding
// names from the bundled .d.ts.

export type {
${entries}
} from 'zod';
`;
};

const run = async () => {
  const names = collectZodNames();
  if (names.length === 0) {
    throw new Error(
      `No Zod* exports found in ${ZOD_DTS}. This usually means zod ` +
        `changed how it ships its public module — review the export ` +
        `filter in scripts/generate-zod-type-exports.ts.`,
    );
  }

  const zodPkg = JSON.parse(await readFile(ZOD_PKG, 'utf8')) as {
    version: string;
  };
  const generated = renderFile(names, zodPkg.version);

  await mkdir(dirname(OUT_FILE), { recursive: true });
  await writeFile(OUT_FILE, generated);

  console.log(
    `[build:zod] wrote ${names.length} Zod* re-exports for zod ${zodPkg.version} → ${OUT_FILE}`,
  );
};

run().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
