/**
 * Generates `src/__generated__/zodTypes.ts` by enumerating every
 * top-level identifier in zod's public modules whose name matches one
 * of veto's "leaky" identifier families:
 *
 *   - `^Zod[A-Z]`            – capitalized class types from `'zod'`
 *                              (`ZodString`, `ZodObject`, …)
 *   - `^\$Zod[A-Z]`          – zod 4 "core" types from `'zod/v4/core'`
 *                              (`$ZodIssueInvalidValue`, …)
 *   - `^_\$Zod[A-Z]`         – zod 4 internal base types from
 *                              `'zod/v4/core'` (`_$ZodType`,
 *                              `_$ZodTypeInternals`)
 *
 * Without these re-exports, consumers' emitted `.d.ts` can fail with
 * `TS4023` ("X cannot be named") when zod types appear in inferred
 * return types of veto APIs — see `docs/veto-monorepo-usage.md`
 * for the full rationale.
 *
 * Wired into `build` (`"build": "pnpm build:zod && tsdown"`), so
 * every build refreshes the snapshot. In CI, fail the job if
 * `git diff --exit-code` is non-clean after `pnpm build`.
 *
 * Source of truth: `node_modules/zod/index.d.ts` (capitalized types)
 * and `node_modules/zod/v4/core/index.d.ts` ($Zod / _$Zod families).
 * Re-export chains are followed via the TypeScript compiler API so
 * this script works even when zod's public d.ts is a re-export barrel.
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';

// typescript is a build-only dependency of veto (used by this codegen
// script). It is intentionally kept in `devDependencies` so it is not
// installed for veto's consumers.
// eslint-disable-next-line import-x/no-extraneous-dependencies
import {
  createProgram,
  ModuleKind,
  ModuleResolutionKind,
  ScriptTarget,
} from 'typescript';

// `pnpm --filter @fuf-stack/veto build:zod` runs with cwd set to the
// package directory, so process.cwd() always resolves to veto's root.
const PKG_ROOT = process.cwd();

const ZOD_DTS = resolve(PKG_ROOT, 'node_modules/zod/index.d.ts');
const ZOD_CORE_DTS = resolve(PKG_ROOT, 'node_modules/zod/v4/core/index.d.ts');
const ZOD_PKG = resolve(PKG_ROOT, 'node_modules/zod/package.json');
const OUT_FILE = resolve(PKG_ROOT, 'src/__generated__/zodTypes.ts');

// Capitalized public class identifiers re-exported from `'zod'`.
const ZOD_NAME_RE = /^Zod[A-Z]/;
// `$Zod*` and `_$ZodType` / `_$ZodTypeInternals` re-exported from
// `'zod/v4/core'` (these are not surfaced at the top level of `'zod'`).
const ZOD_CORE_NAME_RE = /^_?\$Zod[A-Z]/;

/**
 * Enumerates all top-level identifiers exported from `entryDts` whose
 * name matches `nameFilter`. Uses the TS compiler API so re-export
 * barrels are flattened.
 */
const collectExports = (entryDts: string, nameFilter: RegExp): string[] => {
  const program = createProgram({
    rootNames: [entryDts],
    options: {
      module: ModuleKind.ESNext,
      target: ScriptTarget.ESNext,
      moduleResolution: ModuleResolutionKind.Bundler,
      noEmit: true,
      skipLibCheck: true,
    },
  });

  const sourceFile = program.getSourceFile(entryDts);
  if (!sourceFile) {
    throw new Error(`Cannot load ${entryDts}`);
  }

  const checker = program.getTypeChecker();
  const moduleSymbol = checker.getSymbolAtLocation(sourceFile);
  if (!moduleSymbol) {
    throw new Error(`Cannot resolve module symbol for ${entryDts}`);
  }

  return checker
    .getExportsOfModule(moduleSymbol)
    .map((symbol) => {
      return symbol.name;
    })
    .filter((name) => {
      return nameFilter.test(name);
    })
    .sort((a, b) => {
      return a.localeCompare(b);
    });
};

const renderBlock = (specifier: string, names: readonly string[]): string => {
  const entries = names
    .map((name) => {
      return `  ${name},`;
    })
    .join('\n');
  return `export type {\n${entries}\n} from '${specifier}';\n`;
};

const renderFile = (
  zodNames: readonly string[],
  zodCoreNames: readonly string[],
  zodVersion: string,
): string => {
  return `// AUTO-GENERATED by scripts/generate-zod-type-exports.ts — do not edit by hand.
//
// Regenerate with: pnpm --filter @fuf-stack/veto build:zod
// (also runs automatically via \`pnpm --filter @fuf-stack/veto build\`).
//
// Source of truth: node_modules/zod/index.d.ts and
// node_modules/zod/v4/core/index.d.ts (zod ${zodVersion}).
//
// Re-exports the identifier families that leak through veto's API
// surface so consumers' emitted .d.ts can name them. Without these,
// \`tsc --build\` in a consumer raises TS4023 ("X cannot be named").
//
//   - Zod*    – capitalized class types from 'zod'
//   - $Zod*   – zod 4 core types from 'zod/v4/core'
//   - _$Zod*  – zod 4 internal base types from 'zod/v4/core'
//
// A wildcard \`export type * from 'zod'\` is intentionally NOT used:
// zod also exposes lowercase identifiers (\`string\`, \`object\`,
// \`record\`, …) that veto re-uses as its own value-exports — a
// wildcard re-export causes rolldown to silently drop the colliding
// names from the bundled .d.ts.

${renderBlock('zod', zodNames)}
${renderBlock('zod/v4/core', zodCoreNames)}`;
};

const run = async () => {
  const zodNames = collectExports(ZOD_DTS, ZOD_NAME_RE);
  if (zodNames.length === 0) {
    throw new Error(
      `No Zod* exports found in ${ZOD_DTS}. This usually means zod ` +
        `changed how it ships its public module — review the export ` +
        `filter in scripts/generate-zod-type-exports.ts.`,
    );
  }

  const zodCoreNames = collectExports(ZOD_CORE_DTS, ZOD_CORE_NAME_RE);
  if (zodCoreNames.length === 0) {
    throw new Error(
      `No $Zod*/_$Zod* exports found in ${ZOD_CORE_DTS}. This usually ` +
        `means zod restructured its v4 core module — review the export ` +
        `filter in scripts/generate-zod-type-exports.ts.`,
    );
  }

  const zodPkg = JSON.parse(await readFile(ZOD_PKG, 'utf8')) as {
    version: string;
  };
  const generated = renderFile(zodNames, zodCoreNames, zodPkg.version);

  await mkdir(dirname(OUT_FILE), { recursive: true });
  await writeFile(OUT_FILE, generated);

  console.log(
    `[build:zod] wrote ${zodNames.length} Zod* + ${zodCoreNames.length} ` +
      `$Zod*/_$Zod* re-exports for zod ${zodPkg.version} → ${OUT_FILE}`,
  );
};

run().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
