// import veto
import { veto } from './veto';

// export veto typescript types
export type * from './types';
export type * from './vInfer';

// Re-export zod's Zod* type identifiers so consumers' emitted .d.ts
// can name them — prevents TS4023 in consumers. Auto-generated by
// `scripts/generate-zod-type-exports.ts` (runs via `pnpm build:zod`).
export type * from './__generated__/zodTypes';

// export veto issue codes
export * from './issueCodes';

// export serializeSchema helper
export * from './serialize';

// export veto validator types
export * from './types/and/and';
export * from './types/any/any';
export * from './types/array/array';
export * from './types/array/refineArray';
export * from './types/boolean/boolean';
export * from './types/cidrV4/cidrV4';
export * from './types/cidrV6/cidrV6';
export * from './types/discriminatedUnion/discriminatedUnion';
export * from './types/ipV4/ipV4';
export * from './types/ipV6/ipV6';
export * from './types/json/json';
export * from './types/literal/literal';
export * from './types/nativeEnum/nativeEnum';
export * from './types/number/number';
export * from './types/object/object';
export * from './types/object/refineObject';
export * from './types/or/or';
export * from './types/record/record';
export * from './types/string/string';
export * from './types/vEnum/vEnum';

// export veto
export * from './veto';

// also export veto as default
export default veto;
